### PR TITLE
SD3.5 Large support

### PR DESCRIPTION
**Pull request by kohya-ss**
SD3 Medium fine tuning works.

### CODE REVIEW

**Comment by FurkanGozukara** [comment]
awesome can't wait to test it once matured

**Comment by bghira** [comment]
L and G aren't dropped out separately. can't drop out all of clip either due to it being used for adanorm

**Comment by FurkanGozukara** [comment]
@kohya-ss what is the purpose of dropout? so when SAI training they almost dropped out 50% of the times each one randomly? 

so with dropout it is training only U-NET part is that meaning this?

**Comment by bghira** [comment]
this kind of dropout is for pretraining, not for finetuning. for small datasets you will merely harm the model to drop out the text encoders so much. it will overcondition the uncond space.

**Comment by waomodder** [comment]
@kohya-ss
ここでご報告するのもあれですが、ちゃんとSD3.5largeのLoraが学習できてました！
image

image

image

FP8BASEを使用し、learning_rateは1e-4でDim64、alpha 32.0の設定で画像数は約8000枚で24000ステップ回しています。
Loss値は0.1付近で安定して収束していました。

**Comment by deepdelirious** [comment]
The VAE from the huggingface repo for 3.5 won't load - there's a bunch of key mismatches. I was able to get it to work with the SD3 VAE (not sure if they changed anything beyond just renamed layers).

**Comment by dsienra** [comment]
I'm getting this on sd3.5 training, fresh kohya installation.

                     C:/Kohya_installer_v9/kohya_ss/models/sd3\last_20241028-175545.json...
17:55:45-274366 INFO     Executing command: C:\Kohya_installer_v9\kohya_ss\venv\Scripts\accelerate.EXE launch
                         --dynamo_backend no --dynamo_mode default --mixed_precision fp16 --num_processes 1
                         --num_machines 1 --num_cpu_threads_per_process 2
                         C:/Kohya_installer_v9/kohya_ss/sd-scripts/sd3_train.py --config_file
                         C:/Kohya_installer_v9/kohya_ss/models/sd3/config_dreambooth-20241028-175545.toml
C:\Kohya_installer_v9\kohya_ss\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
C:\Kohya_installer_v9\kohya_ss\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
C:\Kohya_installer_v9\kohya_ss\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "C:\Kohya_installer_v9\kohya_ss\sd-scripts\sd3_train.py", line 1076, in <module>
    parser = setup_parser()
  File "C:\Kohya_installer_v9\kohya_ss\sd-scripts\sd3_train.py", line 1061, in setup_parser
    parser.add_argument(
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1441, in add_argument
    return self._add_action(action)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1807, in _add_action
    self._optionals._add_action(action)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1643, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1455, in _add_action
    self._check_conflict(action)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1592, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1601, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --skip_cache_check: conflicting option string: --skip_cache_check
Traceback (most recent call last):
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Kohya_installer_v9\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Kohya_installer_v9\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "C:\Kohya_installer_v9\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "C:\Kohya_installer_v9\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Kohya_installer_v9\\kohya_ss\\venv\\Scripts\\python.exe', 'C:/Kohya_installer_v9/kohya_ss/sd-scripts/sd3_train.py', '--config_file', 'C:/Kohya_installer_v9/kohya_ss/models/sd3/config_dreambooth-20241028-175545.toml']' returned non-zero exit status 1.
17:55:56-459687 INFO     Training has ended.

**Comment by Bocchi-Chan2023** [comment]
- > @kohya-ss ここでご報告するのもあれですが、ちゃんとSD3.5largeのLoraが学習できてました！ image
- > 
- > image
- > 
- > image
- > 
- > FP8BASEを使用し、learning_rateは1e-4でDim64、alpha 32.0の設定で画像数は約8000枚で24000ステップ回しています。 Loss値は0.1付近で安定して収束していました。
- 

使用したオプティマイザを教えていただけるとありがたいです

**Comment by waomodder** [comment]
@Bocchi-Chan2023 
オプティマイザーはAdamW8bitを使用し、スケジューラーはcosineとなってます。

**Comment by nephi-dev** [comment]
can't load the VAE, either 3.5 and 3, i'm getting an Missing key error

**Comment by nephi-dev** [comment]
> can't load the VAE, either 3.5 and 3, i'm getting an Missing key error

actully, i've managed to extract the VAE directly from sd3 and it did work now, maybe I was using an wrong one

**Comment by nephi-dev** [comment]
do you have an minimum params config to train an LoRA on sd35M? i've tried with some configs(that i've used for flux), yet no results at all

**Comment by FurkanGozukara** [comment]
> `--disable_mmap_load_safetensors`

why is this not default? what is the reason not making it default? thank you

**Pull request merged**
