### PR TITLE
Add Karras post-hoc EMA

### PR DESCRIPTION
**Pull request by vvern999**
This allows to generate different EMA profiles after training, without having to retrain.
Explanation of the method:  https://github.com/cloneofsimo/karras-power-ema-tutorial
Traditional EMA implementation is based on https://github.com/lucidrains/ema-pytorch

**Only train_network and sdxl_train_network are supported currently.**

### How to use:
Add `--enable_ema --ema_type="post-hoc"` to training options. `--ema_on_gpu` to use gpu.
It will save snapshots in `OUTPUT_DIR/OUTPUT_NAME_snapshots`
After training you can generate EMA checkpoints with `python .\tools\reconstruct_ema_weights.py PATH_TO_SNAPSHOT_FOLDER --target_gamma GAMMA`

Different values of gamma correspond to different "averaging length" sigma_rel. You can use `--target_sigma_rel` instead of gamma.
Screenshot 2024-02-01 151122

### Examples of different gamma:
SD1.5:
xyz_grid-resized
SDXL: 
resize-25

Different models may require different gamma for best results.

### CODE REVIEW

**Comment by feffy380** [comment]
100 is an extremely high value for gamma. Based on the explanation [here](https://github.com/cloneofsimo/karras-power-ema-tutorial), high values of gamma make the response time (averaging period) shorter. With gamma=100 you're essentially getting instant response, which completely negates whatever benefit EMA is supposed to bring.

You need to include a control test with no EMA. I suspect it will look very similar to the high gamma profiles.

**Comment by vvern999** [comment]
@feffy380 
You are right, gamma=100 looks same as a model without ema, and with low gamma it looks same as no lora. 
As far as i understand, Lora is initialized with zeros, so with high averaging it just averages to 0. 

There's an option to start EMA updates only after x steps - `--ema_update_after_step`. I guess it may help, but it doesn't work right now
Also those lora are trained only for 750 steps, averaging is probably not practically useful with such low number of steps. People usually use EMA when training on thousands or millions of images for many steps

xyz_grid-3439-1953469724-best quality,_1girl, amane kanata, amane kanata 6th costume, ahoge, angel, angel wings, arm at side, hair ornament, black collar

**Comment by FurkanGozukara** [comment]
from these experiment anime pictures i really can't understand quality

can't you test on a random guy face so we can see how much improvement it has?

**Comment by dill-shower** [comment]
Any plans to update it for full finetune models?

**Comment by gesen2egee** [comment]
Hello, I noticed that you've removed the args option for the traditional EMA. I'd like to know if the functionality of the traditional EMA is working fine now?

**Comment by vvern999** [comment]
@gesen2egee  @dill-shower 
Sorry, I don't have the time or interest to test or finish this.
Traditional EMA worked in previous commits, but it didn't seem very useful.
I'm not sure if it's just not useful for a short training or if I made a mistake somewhere and it was not working correctly. 
Maybe someone else will implement it properly

**Comment by CelesteHargreeves** [comment]
Will there be EMA for Flux Dev?

**Pull request closed without merging**
