### PR TITLE
add lora_fa

### PR DESCRIPTION
**Pull request by kohya-ss**

### CODE REVIEW

**Comment by feffy380** [comment]
Is that system memory or vram?

**Comment by evshiron** [comment]
@kohya-ss 

Greetings. Do you have an ETA for merging the dev branch to main? A PR https://github.com/vladmandic/automatic/pull/2009 is currently waiting for it.

**Comment by feffy380** [comment]
I saw vram usage increase from 10.7GB to 11.3GB. Speed increase was only about 3-4%. It doesn't seem to be worth using in the current state

**Comment by feffy380** [comment]
@kohya-ss I printed out the `network.parameters()` right before the training loop and it looks like the lora_down modules aren't getting frozen (True is output of requires_grad)
image

Additionally, `LoRAModule.requires_grad_()` never gets called. The `network.requires_grad_()` call doesn't seem to propagate to it.

**Pull request merged**
