### PR TITLE
Caching latents and Text Encoder outputs with multiple GPUs

### PR DESCRIPTION
**Pull request by kohya-ss**

### CODE REVIEW

**Comment by FurkanGozukara** [comment]
awesome. this will work automatically when multi gpu used?

**Comment by FurkanGozukara** [comment]
@kohya-ss those --highvram and --lowvram made 0 impact on my testings previously what they do actually? I tested both for FLUX Fine tuning and FLUX LoRA training

I can test FLUX LoRA multi gpu caching - fine tuning still requires 80 gb GPUs, fused backward pass not working

**Comment by FurkanGozukara** [comment]
@kohya-ss you are awesome thank you so much

**Comment by SoonNOON** [comment]
I hope the full version of GPT 01 will help find the right solution very soon.

**Comment by sdbds** [comment]
I hope it is possible to push the cached data directly to HF, so that pulling latents directly in the cloud platform will not take up cache time, and more hard disk space can be saved on large datasets.

**Pull request merged**
